---
title: "test"
author: "Hilary Killam"
date: "29/04/2021"
output: html_document
---

```{r setup, include=FALSE}

renv::restore() #restore from renv snapshot to make sure project uses correct version of packages

```

```{r}

data_full_trials_unfiltered_1a_2 %>%
  filter(trial_from_zero >= ANTICIP_START_OFF & trial_from_zero <= ANTICIP_END_OFF) %>%
  group_by(trial_unique, trial_type) %>%
  summarize(prop_fixations = mean(look_any),
            prop_target = sum(target)/sum(look_any),
         length_looking_any = sum(look_any)*(1000/60),
         length_looking_target = sum(target*(1000/60))) %>% 
  ungroup() %>%
  ggplot() +
  geom_histogram(aes(x = length_looking_any)) +
  facet_wrap(~ trial_type) +
  ggtitle("Distribution of looking length to any AOI during trials") +
  labs(x = "length looking to any AOI (ms)",
       y = "# trials")

data_full_trials_unfiltered_1a_2 %>%
  filter(trial_from_zero >= ANTICIP_START_OFF & trial_from_zero <= ANTICIP_END_OFF) %>%
  group_by(trial_unique, trial_type) %>%
  filter(sum(look_any) > 0) %>%
  summarize(prop_fixations = mean(look_any),
         length_looking_any = sum(look_any)*(1000/60),
         length_looking_target = sum(target*(1000/60))) %>% 
  ungroup() %>%
  ggplot(aes(x = length_looking_target)) +
  geom_histogram() +
  facet_wrap(~trial_type) +
  ggtitle("Distribution of looking length to Target during trials with any looking") +
  labs(x = "length looking to Target AOI (ms)",
       y = "# trials")


data_full_trials_unfiltered_1a_2 %>%
  filter(trial_from_zero >= ANTICIP_START_OFF & trial_from_zero <= ANTICIP_END_OFF) %>%
  group_by(trial_unique) %>%
  summarize(prop_fixations = mean(look_any),
         length_looking_any = sum(look_any)*(1000/60),
         length_looking_target = sum(target*(1000/60)),
         looking_less_100 = ifelse(length_looking_any >= 100, 0, 1),
         looking_less_200 = ifelse(length_looking_any >= 200, 0, 1),
         looking_less_500 = ifelse(length_looking_any >= 500, 0, 1)) %>% 
  ungroup() %>%
  summarize(prop_excl_100 = mean(looking_less_100),
            prop_excl_200 = mean(looking_less_200),
            prop_excl_500 = mean(looking_less_500)) %>%
  pivot_longer(everything(), names_to = "exclusion_length", values_to = "proportion_excluded") %>%
  mutate(exclusion_length = paste(parse_number(exclusion_length), "ms")) %>%
  ggplot(aes(x = exclusion_length, y = proportion_excluded)) +
  geom_col() +
  ggtitle("Proportion of trials excluded by various looking length cutoffs") +
  xlab("Exclusion cutoff looking time (ms)") +
  ylab("Proportion of trials excluded") +
  geom_text(aes(label = round(proportion_excluded, digits = 2)), vjust = 1.5, color = "white")

```
